

Spring:
  datasource:
    password: 240929
    username: root
    url: jdbc:mysql://localhost:3306/message?serverTimeZone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    prefix:
    suffix: .jsp



#  thymeleaf:
#    prefix: classpath:/
#    suffix: .html
#    mode: HTML
#    cache: false



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #    log-impl??????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  servlet:
    context-path: /

